import type { PrimaryWeaponType, SecondaryWeaponType } from './types';

export const primaryWeapons: PrimaryWeaponType[] = [
	{
		name: 'AR-23 Liberator',
		category:'Assault Rifle',
		description: 'The SEAF standard assault rifle, balancing power, fire rate, and weight for a reliable weapon against smaller targets.',
		damage: 70,
		capacity: 45,
		fireRate: 14,
		recoil: 640,
		traits: ['Light Armor Penetrating'],
		image: 'liberator.webp',
	},
	{
		name: 'AR-23P Liberator Penetrator',
		category:'Assault Rifle',
		description: 'A modified Liberator fitted with a scope and firing armor-piercing rounds, to help users take down armored targets.',
		damage: 60,
		capacity: 45,
		fireRate: 18,
		recoil: 640,
		traits: ['Medium Armor Penetrating'],
		image: 'liberator-penetrator.webp',
	},
	{
		name: 'AR-23A Liberator Carbine',
		category:'Assault Rifle',
		description: 'A compact version of the Liberator designed for increased viability in close quarters. Has an increased fire rate at the cost of higher spread.',
		damage: 70,
		capacity: 45,
		fireRate: 25,
		recoil: 920,
		traits: ['Light Armor Penetrating'],
		image: 'liberator-carbine.webp',
	},
	{
		name: 'AR-23C Liberator Concussive',
		category:'Assault Rifle',
		description: 'A modified Liberator featuring explosive rounds and a red-dot sight. Trades increased damage for increased recoil.',
		damage: 65,
		capacity: 60,
		fireRate: 28,
		recoil: 320,
		traits: ['Light Armor Penetrating'],
		image: 'liberator-concussive.webp',
	},
	{
		name: 'AR-61 Tenderizer',
		category:'Assault Rifle',
		description: 'A high-caliber assault rifle with a restrictive magazine size but more stopping power.',
		damage: 95,
		capacity: 35,
		fireRate: 10,
		recoil: 600,
		traits: ['Light Armor Penetrating'],
		image: 'tenderizer.webp',
	},
	{
		name: 'BR-14 Adjudicator',
		category:'Assault Rifle',
		description: 'An accurate, armor-penetrating rifle, the BR-14 Adjudicator delivers righteous judgement to medium-sized enemies, though its restrictive magazine limits its effectiveness against large groups.',
		damage: 90,
		capacity: 30,
		fireRate: 38,
		recoil: 550,
		traits: ['Medium Armor Penetrating'],
		image: 'adjudicator.webp',
	},
	{
		name: 'SG-8 Punisher',
		category: 'Shotgun',
		description: 'A powerful dual magazine pump-action shotgun, with limited armor penetration. Ideal for small and fast targets.',
		damage: 405,
		capacity: 16,
		recoil: 120,
		fireRate: 80,
		traits: ['Light Armor Penetrating', 'Rounds Reload'],
		image: 'punisher.webp',
	}
	{
		name: 'R-63 Diligence',
		category: 'Marksman Rifle',
		description:'This high-caliber marksman rifle trades magazine capacity and rate of fire for powerful, accurate shots.',
		damage: 165,
		capacity: 20,
		recoil: 35,
		fireRate: 350,
		traits: ['Light Armor Penetrating'],
		image: 'diligence.webp',
	},
	{
		name: 'SMG-37 Defender',
		category: 'Submachine Gun',
		description: 'A high-caliber submachine gun which can be fired with one hand. Has a relatively low rate of fire.',
		damage: 75,
		capacity: 45,
		recoil: 10,
		fireRate: 520,
		traits: ['Light Armor Penetrating', 'One Handed'],
		image: 'defender.webp',
	},
	{
		name: 'SG-225 Breaker',
		category: 'Shotgun',
		description: 'A fully-automatic shotgun with a high rate of fire, excellent for controlling crowds. Requires frequent reloading.',
		damage: 330,
		capacity: 16,
		recoil: 55,
		fireRate: 300,
		traits: ['Light Armor Penetrating'],
		image: 'breaker.webp',
	},
	{
		name: 'LAS-5 Scythe',
		category: 'Energy-Based',
		description: 'A laser rifle firing a continuous beam. Does not need reloading, but if it overheats a new heat sink must be fitted.',
		damage: 350,
		capacity: 8,
		recoil: 0,
		fireRate: 0,
		traits: ['Light Armor Penetrating', 'Beam', 'Heat'],
		image: 'scythe.webp',
	},
	{
		name: 'R-63CS Diligence Counter Sniper',
		category: 'Marksman Rifle',
		description: 'A modified Diligence rifle offering increased damage, but a reduced rate of fire. Fires a single bullet at a time.',
		damage: 200,
		capacity: 15,
		recoil: 53,
		fireRate: 350,
		traits: ['Medium Armor Penetrating'],
		image: 'diligence-counter-sniper.webp',
	},
	{
		name: 'SG-8S Slugger',
		category: 'Shotgun',
		description: 'A modified Punisher shotgun firing heavy, high-damage slug rounds. Perfect for punching holes in big targets.',
		damage: 250,
		capacity: 16,
		recoil: 120,
		fireRate: 80,
		traits: ['Medium Armor Penetrating', 'Rounds Reload'],
		image: 'slugger.webp',
	},
	{
		name: 'SG-225SP Breaker Spray&Pray',
		category: 'Shotgun',
		description: 'A modified Breaker shotgun firing birdshot, small pellets which saturate an area to clear up smaller targets.',
		damage: 240,
		capacity: 46,
		recoil: 25,
		fireRate: 330,
		traits: ['Light Armor Penetrating'],
		image: 'breaker-spray-and-pray.webp',
	},
	{
		name: 'PLAS-1 Scorcher',
		category: 'Energy-Based',
		description: 'A plasma rifle, firing a bolt of superheated gas which explodes on impact. Avoid standing in proximity to the blast.',
		damage: 200,
		capacity: 20,
		recoil: 20,
		fireRate: 350,
		traits: ['Medium Armor Penetrating', 'Explosive'],
		image: 'scorcher.webp',
	},
	{
		name: 'SG-225IE Breaker Incendiary',
		category: 'Shotgun',
		description: 'A modified Breaker shotgun firing incendiary projectiles. Generates heat during use, so limited to burst fire.',
		damage: 240,
		capacity: 25,
		recoil: 41,
		fireRate: 300,
		traits: ['Light Armor Penetrating', 'Incendiary'],
		image: 'breaker-incendiary.webp',
	},
	{
		name: 'JAR-5 Dominator',
		category: 'Special',
		description: 'Firing jet-propelled rounds, the Dominator trades fire rate and magazine capacity for increased damage per projectile.',
		damage: 275,
		capacity: 15,
		recoil: 75,
		fireRate: 250,
		traits: ['Medium Armor Penetrating'],
		image: 'dominator.webp',
	},
	{
		name: 'LAS-16 Sickle',
		category: 'Energy-Based',
		description: 'A laser rifle, firing in short bursts. Does not need reloading, but if it overheats a new heat sink must be fitted.',
		damage: 55,
		capacity: 7,
		recoil: 2,
		fireRate: 750,
		traits: ['Light Armor Penetrating', 'Heat'],
		image: 'sickle.webp',
	},
	{
		name: 'ARC-12 Blitzer',
		category: 'Energy-Based',
		description: 'This shotgun blasts a wide burst of high-voltage electricity that arcs between all units - enemy or otherwise - within range.',
		damage: 250,
		capacity: -1,
		recoil: 60,
		fireRate: 45,
		traits: ['Medium Armor Penetrating'],
		image: 'blitzer.webp',
	},
	{
		name: 'R-36 Eruptor',
		category: 'Explosive',
		description: 'This bolt-action rifle fires jet-assisted shells that explode shrapnel in all directions upon impact. Not recommended for close-quarters use.',
		damage: 455,
		capacity: 5,
		recoil: 75,
		fireRate: 25,
		traits: ['Medium Armor Penetrating', 'Explosive'],
		image: 'eruptor.webp',
	},
	{
		name: 'CB-9 Exploding Crossbow',
		category: 'Explosive',
		description:'Fires powerful exploding bolts that do maximum damage upon direct impact. Gravity must be accounted for when aiming.',
		damage: 620,
		capacity: 5,
		recoil: 35,
		fireRate: 50,
		traits: ['Medium Armor Penetrating', 'Explosive'],
		image: 'exploding-crossbow.webp',
	}

];



export const secondaryWeapons: SecondaryWeaponType[] = [
	// TODO: add the peacemaker from ingame stats
	{
		name: 'P-19 Redeemer',
		category: 'Pistol',
		description:'A fully-automatic pistol with an extremely high fire rate, allowing for efficient crowd control.',
		damage: 60,
		capacity: 31,
		recoil: 1100,
		fireRate: 15,
		traits: ['Light Armor Penetrating', 'One Handed'],
		image: 'redeemer.webp',
	},
	{
		name: 'P-4 Senator',
		category: 'Pistol',
		description: 'A high-damage revolver, which can be reloaded with single rounds. A heavy-hitting and reliable sidearm.',
		damage: 200,
		capacity: 6,
		recoil: 43,
		fireRate: 200,
		traits: ['Heavy Armor Penetrating', 'Rounds Reload', 'One Handed'],
		image: 'senator.webp',
	},
]

export const grenades = [
	'frag',
	'high explosive',
	'incendiary',
	'impact',
	'incendiary impact',
	'stun',
	'smoke',
	'thermite',
	'throwing knife'
]


export const stratagemsDB = [
	'Jump Pack',
	'Supply Pack',
	'Guard Dog Rover',
	'Guard Dog',
	'Ballistic Shield',
	"Shield Generator",
	"Machine Gun",
	"Anti-Material Rifle",
	"Stalwart",
	"Expendable Anti-Tank",
	"Commando",
	"Recoilless Rifle",
	"Flamethrower",
	"Auto cannon",
	"Heavy Machine Gun",
	"Machine Gun",
	"Railgun",
	"Spear",
	"grenade launcher",
	"Laser cannon",
	"Arc Thrower",
	"Quasar Cannon",
	"Airburst Rocket launcher",
	"Patriot Exosuit",
	"Emancipator Exosuit",
	"MG Emplacement",
	"Shield Generator",
	"Tesla Tower",
	"Anti-Personnel Minefield",
	"incendiary mines",
	"anti-tank mines",
	'machine-gun sentry',
	'gatling sentry',
	'mortar sentry',
	'autocannon sentry',
	'rocket sentry',
	'EMS mortar sentry',
	'orbital gatling barrage',
	'orbital airburst',
	'orbital 120mm barrage',
	'orbital 380mm barrage',
	'orbital walking barrage',
	'orbital laser',
	'orbital railcannon',
	'orbital precision strike',
	'orbital gas strike',
	'orbital EMS strike',
	'orbital smoke strike',
	'eagle strafing run',
	'eagle airstrike',
	'eagle cluster bomb',
	'eagle napalm strike',
	'eagle smoke strike',
	'eagle 110mm rocket pod',
	'eagle 500kg bomb',
	'napalm orbital strike'
]

export const boosters = [ "Hellpod Space Optimization",   "Vitality Enhancement",   "UAV Recon Booster",   "Stamina Enhancement",   "Muscle Enhancement",   "Increased Reinforcement Budget",   "Flexible Reinforcement Budget",   "Localization Confusion Booster",   "Expert Extraction Pilot Booster",   "Motivational Shocks",   "Experimental Infusion",   "Firebomb Hellpods", "Dead Sprint" ]