export const primaryWeapons = [
	'Liberator',
	'Liberator Penetrator',
	'Liberator Concussive',
	'Liberator Carbine',
	"tenderizer",
	"Adjudicator",
	"AR-2 'Diligence' Marksman Rifle",
	"AR-63s 'Diligence Counter Sniper' Marksman Rifle",
	"Knight",
	"Defender",
	"Pummeler",
	"Punisher",
	"Slugger",
	"Cookout",
	"Breaker",
	"Breaker incendiary",
	"Breaker Spray and Pray",
	"Crossbow",
	"Dominator",
	"Eruptor",
	"Punisher Plasma",
	"Arc Blitzer",
	"Scythe",
	"Sickle",
	"scorcher",
	"Purifier",
	"Torcher",
	"Halt",
	"Reprimand",
	"constitution"
];

export const secondaryWeapons = [
	'peacemaker',
	'redeemer',
	'verdict',
	'senator',
	'bushwacker',
	'crisper',
	'grenade pistol',
	'dagger',
	"loyalist",
]

export const grenades = [
	'frag',
	'high explosive',
	'incendiary',
	'impact',
	'incendiary impact',
	'stun',
	'smoke',
	'thermite',
	'throwing knife'
]


export const stratagemsDB = [
	'Jump Pack',
	'Supply Pack',
	'Guard Dog Rover',
	'Guard Dog',
	'Ballistic Shield',
	"Shield Generator",
	"Machine Gun",
	"Anti-Material Rifle",
	"Stalwart",
	"Expendable Anti-Tank",
	"Commando",
	"Recoilless Rifle",
	"Flamethrower",
	"Auto cannon",
	"Heavy Machine Gun",
	"Machine Gun",
	"Railgun",
	"Spear",
	"grenade launcher",
	"Laser cannon",
	"Arc Thrower",
	"Quasar Cannon",
	"Airburst Rocket launcher",
	"Patriot Exosuit",
	"Emancipator Exosuit",
	"MG Emplacement",
	"Shield Generator",
	"Tesla Tower",
	"Anti-Personnel Minefield",
	"incendiary mines",
	"anti-tank mines",
	'machine-gun sentry',
	'gatling sentry',
	'mortar sentry',
	'autocannon sentry',
	'rocket sentry',
	'EMS mortar sentry',
	'orbital gatling barrage',
	'orbital airburst',
	'orbital 120mm barrage',
	'orbital 380mm barrage',
	'orbital walking barrage',
	'orbital laser',
	'orbital railcannon',
	'orbital precision strike',
	'orbital gas strike',
	'orbital EMS strike',
	'orbital smoke strike',
	'eagle strafing run',
	'eagle airstrike',
	'eagle cluster bomb',
	'eagle napalm strike',
	'eagle smoke strike',
	'eagle 110mm rocket pod',
	'eagle 500kg bomb',
	'napalm orbital strike'
]

export const boosters = [ "Hellpod Space Optimization",   "Vitality Enhancement",   "UAV Recon Booster",   "Stamina Enhancement",   "Muscle Enhancement",   "Increased Reinforcement Budget",   "Flexible Reinforcement Budget",   "Localization Confusion Booster",   "Expert Extraction Pilot Booster",   "Motivational Shocks",   "Experimental Infusion",   "Firebomb Hellpods", "Dead Sprint" ]