import type { PrimaryWeaponType, SecondaryWeaponType } from './types';

// export const primaryWeapons: PrimaryWeaponType[] = [
// 	{
// 		name: 'AR-23 Liberator',
// 		category:'Assault Rifle',
// 		description: 'The SEAF standard assault rifle, balancing power, fire rate, and weight for a reliable weapon against smaller targets.',
// 		damage: 70,
// 		capacity: 45,
// 		fireRate: 14,
// 		recoil: 640,
// 		traits: ['Light Armor Penetrating'],
// 		image: 'liberator.webp',
// 	},
// 	{
// 		name: 'AR-23P Liberator Penetrator',
// 		category:'Assault Rifle',
// 		description: 'A modified Liberator fitted with a scope and firing armor-piercing rounds, to help users take down armored targets.',
// 		damage: 60,
// 		capacity: 45,
// 		fireRate: 18,
// 		recoil: 640,
// 		traits: ['Medium Armor Penetrating'],
// 		image: 'liberator-penetrator.webp',
// 	},
// 	{
// 		name: 'AR-23A Liberator Carbine',
// 		category:'Assault Rifle',
// 		description: 'A compact version of the Liberator designed for increased viability in close quarters. Has an increased fire rate at the cost of higher spread.',
// 		damage: 70,
// 		capacity: 40,
// 		fireRate: 25,
// 		recoil: 920,
// 		traits: ['Light Armor Penetrating'],
// 		image: 'liberator-carbine.webp',
// 	},
// 	{
// 		name: 'AR-23C Liberator Concussive',
// 		category:'Assault Rifle',
// 		description: 'A modified Liberator featuring explosive rounds and a red-dot sight. Trades increased damage for increased recoil.',
// 		damage: 65,
// 		capacity: 60,
// 		fireRate: 28,
// 		recoil: 320,
// 		traits: ['Light Armor Penetrating'],
// 		image: 'liberator-concussive.webp',
// 	},
// ];
export const primaryWeapons = [
	'Liberator',
	'Liberator Penetrator',
	'Liberator Concussive',
	'Liberator Carbine',
	"tenderizer",
	"Adjudicator",
	"AR-2 'Diligence' Marksman Rifle",
	"AR-63s 'Diligence Counter Sniper' Marksman Rifle",
	"Knight",
	"Defender",
	"Pummeler",
	"Punisher",
	"Slugger",
	"Cookout",
	"Breaker",
	"Breaker incendiary",
	"Breaker Spray and Pray",
	"Crossbow",
	"Dominator",
	"Eruptor",
	"Punisher Plasma",
	"Arc Blitzer",
	"Scythe",
	"Sickle",
	"scorcher",
	"Purifier",
	"Torcher",
	"Halt",
	"Reprimand",
	"constitution"
];

export const secondaryWeapons = [
	'peacemaker',
	'redeemer',
	'verdict',
	'senator',
	'bushwacker',
	'crisper',
	'grenade pistol',
	'dagger',
	"loyalist",
]

export const grenades = [
	'frag',
	'high explosive',
	'incendiary',
	'impact',
	'incendiary impact',
	'stun',
	'smoke',
	'thermite',
	'throwing knife'
]


export const stratagemsDB = [
	'Jump Pack',
	'Supply Pack',
	'Guard Dog Rover',
	'Guard Dog',
	'Ballistic Shield',
	"Shield Generator",
	"Machine Gun",
	"Anti-Material Rifle",
	"Stalwart",
	"Expendable Anti-Tank",
	"Commando",
	"Recoilless Rifle",
	"Flamethrower",
	"Auto cannon",
	"Heavy Machine Gun",
	"Machine Gun",
	"Railgun",
	"Spear",
	"grenade launcher",
	"Laser cannon",
	"Arc Thrower",
	"Quasar Cannon",
	"Airburst Rocket launcher",
	"Patriot Exosuit",
	"Emancipator Exosuit",
	"MG Emplacement",
	"Shield Generator",
	"Tesla Tower",
	"Anti-Personnel Minefield",
	"incendiary mines",
	"anti-tank mines",
	'machine-gun sentry',
	'gatling sentry',
	'mortar sentry',
	'autocannon sentry',
	'rocket sentry',
	'EMS mortar sentry',
	'orbital gatling barrage',
	'orbital airburst',
	'orbital 120mm barrage',
	'orbital 380mm barrage',
	'orbital walking barrage',
	'orbital laser',
	'orbital railcannon',
	'orbital precision strike',
	'orbital gas strike',
	'orbital EMS strike',
	'orbital smoke strike',
	'eagle strafing run',
	'eagle airstrike',
	'eagle cluster bomb',
	'eagle napalm strike',
	'eagle smoke strike',
	'eagle 110mm rocket pod',
	'eagle 500kg bomb',
	'napalm orbital strike'
]

export const boosters = [ "Hellpod Space Optimization",   "Vitality Enhancement",   "UAV Recon Booster",   "Stamina Enhancement",   "Muscle Enhancement",   "Increased Reinforcement Budget",   "Flexible Reinforcement Budget",   "Localization Confusion Booster",   "Expert Extraction Pilot Booster",   "Motivational Shocks",   "Experimental Infusion",   "Firebomb Hellpods", "Dead Sprint" ]